---
name: VyOS 1.3 Autobuild

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * SAT'

jobs:
  build-iso:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    permissions:
      contents: write

    container:
      image: vyos/vyos-build:equuleus
      env:
        TZ: Australia/Brisbane
      options: --privileged

    steps:
      - name: Clone the `vyos-build` repository
        id: clone-upstream
        run: |
          set -eux
          git clone -b equuleus --single-branch https://github.com/vyos/vyos-build

      - name: Get the latest upstream tag
        id: get-upstream-tag
        working-directory: vyos-build
        run: |
          echo "latest=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

      - name: Checkout the `vyos-build` repository to the latest upstream tag
        id: checkout-upstream-tag
        working-directory: vyos-build
        run: |
          set -eux
          git checkout tags/${{ steps.get-upstream-tag.outputs.latest }}

      - name: Configure the VyOS build
        id: configure-build
        working-directory: vyos-build
        run: |
          set -eux
          ./configure --architecture amd64 --build-by vyos-autobuild@tech.bymatt.au --build-type release --version ${{ steps.get-upstream-tag.outputs.latest }}

      - name: Build the VyOS ISO
        id: build-iso
        working-directory: vyos-build
        run: |
          set -eux
          make iso

      - name: Create a new release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          name: "VyOS ${{ steps.get-upstream-tag.outputs.latest }}"
          tag: "${{ steps.get-upstream-tag.outputs.latest }}"
          artifacts: "vyos-build/build/vyos-${{ steps.get-upstream-tag.outputs.latest }}-amd64.iso"
          artifactContentType: application/x-iso9660-image
          draft: true
          allowUpdates: true
          omitDraftDuringUpdate: true
